### ISSUE TITLE
Awesome idea but I'm stuck with this error

### ISSUE THREAD

**Issue by MarcusSinclair** [sirupsen/anki-airtable#19]
Any help would lead to immediate gratification.

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.47 (dc156f34) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.15.7
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-09-04 00:40:46
Add-ons possibly involved: ⁨Airtable Anki⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/progress.py", line 54, in handler
  File "aqt/main.py", line 150, in on_window_init
  File "aqt/main.py", line 245, in setupProfile
  File "aqt/main.py", line 425, in loadProfile
  File "aqt/hooks_gen.py", line 2951, in __call__
  File "anki/hooks.py", line 34, in runHook
  File "/Users/marcussinclair/Library/Application Support/Anki2/addons21/1573217784/__init__.py", line 186, in hook
    airtableImport(mw.col, table["anki_deck"], table["anki_model"], table["airtable_table"], table["airtable_view"], table["airtable_key"])
  File "/Users/marcussinclair/Library/Application Support/Anki2/addons21/1573217784/__init__.py", line 163, in airtableImport
    mw.col.models.add(model)
  File "anki/models.py", line 204, in add
  File "anki/_backend/generated.py", line 438, in add_notetype_legacy
  File "anki/_backend/__init__.py", line 131, in _run_command
anki.errors.InvalidInput: Invalid input: ⁨1 field required⁩

**Comment by sirupsen** [comment]
Hey Marcus, I don't really use this myself anymore, likely things changed with Anki 2.1. Sorry.
